package com.matejpcs.netflared;
import com.google.gson.*;import java.io.*;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Duration;import java.util.*;import java.util.concurrent.*;import java.util.function.*;
public final class NetflaredCore{
 public interface Sender{boolean admin();void send(String s);} public record ServerInfo(int port,String name){}
 private final Path dir,configFile,tokenFile,binary;private final Supplier<ServerInfo> server;private final Consumer<Runnable> main;private final HttpClient http=HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).build();private Process process;private volatile List<JsonObject> zones=List.of();private volatile String setupToken="";
 public NetflaredCore(Path d,Supplier<ServerInfo>s,Consumer<Runnable>m)throws IOException{dir=d;Files.createDirectories(d);configFile=d.resolve("config.json");tokenFile=d.resolve("tunnel.token");server=s;main=m;binary=d.resolve("bin").resolve(System.getProperty("os.name","").toLowerCase().contains("win")?"cloudflared.exe":"cloudflared");if(!Files.exists(configFile))save(new JsonObject());}
 private JsonObject load()throws IOException{JsonObject o=JsonParser.parseString(Files.readString(configFile)).getAsJsonObject();return o;}private void save(JsonObject o)throws IOException{Files.writeString(configFile,new GsonBuilder().setPrettyPrinting().create().toJson(o));}
 private String v(JsonObject o,String k){return o.has(k)?o.get(k).getAsString():"";}private boolean configured(JsonObject o){return o.get("enabled")!=null&&o.get("enabled").getAsBoolean()&&!v(o,"tunnelToken").isBlank()&&!v(o,"tunnelId").isBlank();}
 public void shutdown(){if(process!=null){process.destroy();process=null;}}
 public void autoConnect(){try{if(configured(load()))connect(null);}catch(Exception ignored){}}
 public void handle(Sender s,String[]a){if(!s.admin()){s.send("§cYou do not have permission to manage Netflared.");return;}String x=a.length==0?"status":a[0].toLowerCase(Locale.ROOT);switch(x){case"status"->status(s);case"info"->info(s);case"connect","start"->connect(s);case"disconnect","stop"->{shutdown();s.send("§eCloudflared stopped.");}case"setup"->setup(s,a);case"reset"->reset(s);default->help(s);}}
 private void setup(Sender s,String[]a){if(a.length<2){s.send("§e/netflared setup <cloudflare-api-token>");s.send("§7/netflared setup select <number> [subdomain]");return;}if("select".equalsIgnoreCase(a[1])){if(a.length<3){s.send("§cChoose a zone number.");return;}try{select(s,Integer.parseInt(a[2]),a.length>3?a[3]:"play");}catch(Exception e){s.send("§cZone number must be a number.");}return;}begin(s,a[1]);}
 private void begin(Sender s,String token){if(token.length()<20){s.send("§cThat does not look like a Cloudflare API token.");return;}setupToken=token;s.send("§eChecking Cloudflare API token...");CompletableFuture.runAsync(()->{try{String body=request("GET","https://api.cloudflare.com/client/v4/zones?per_page=100",null,token);JsonArray r=JsonParser.parseString(body).getAsJsonObject().getAsJsonArray("result");if(r.isEmpty())throw new IOException("No Cloudflare zones are visible to this token.");List<JsonObject>z=new ArrayList<>();for(JsonElement e:r)z.add(e.getAsJsonObject());zones=z;main.accept(()->{s.send("§aCloudflare token accepted. Choose a domain:");for(int i=0;i<z.size();i++)s.send("§e"+(i+1)+"§7. "+z.get(i).get("name").getAsString());s.send("§7/netflared setup select <number> [subdomain]");});}catch(Exception e){main.accept(()->s.send("§cSetup failed: "+e.getMessage()));}});}
 private void select(Sender s,int n,String sub){if(zones.isEmpty()){s.send("§cNo setup session is active.");return;}if(n<1||n>zones.size()){s.send("§cInvalid zone number.");return;}JsonObject z=zones.get(n-1);String zone=z.get("name").getAsString(),host=sub+"."+zone;ServerInfo si=server.get();String rawName=("netflared-"+si.name()).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9-]","-");final String name=rawName.substring(0,Math.min(48,rawName.length()));s.send("§eCreating Cloudflare Tunnel for "+host+"...");CompletableFuture.runAsync(()->{try{String account=z.getAsJsonObject("account").get("id").getAsString();JsonObject b=new JsonObject();b.addProperty("name",name);b.addProperty("config_src","cloudflare");JsonObject t=JsonParser.parseString(request("POST","https://api.cloudflare.com/client/v4/accounts/"+account+"/cfd_tunnel",b,setupToken)).getAsJsonObject().getAsJsonObject("result");String id=t.get("id").getAsString();String tok=JsonParser.parseString(request("GET","https://api.cloudflare.com/client/v4/accounts/"+account+"/cfd_tunnel/"+id+"/token",null,setupToken)).getAsJsonObject().get("result").getAsString();JsonArray ingress=new JsonArray();JsonObject route=new JsonObject();route.addProperty("hostname",host);route.addProperty("service","tcp://localhost:"+si.port());ingress.add(route);JsonObject fb=new JsonObject();fb.addProperty("service","http_status:404");ingress.add(fb);JsonObject cfg=new JsonObject();cfg.add("ingress",ingress);JsonObject body=new JsonObject();body.add("config",cfg);request("PUT","https://api.cloudflare.com/client/v4/accounts/"+account+"/cfd_tunnel/"+id+"/configurations",body,setupToken);JsonObject dns=new JsonObject();dns.addProperty("type","CNAME");dns.addProperty("name",host);dns.addProperty("content",id+".cfargotunnel.com");dns.addProperty("ttl",1);dns.addProperty("proxied",true);request("POST","https://api.cloudflare.com/client/v4/zones/"+z.get("id").getAsString()+"/dns_records",dns,setupToken);JsonObject c=new JsonObject();c.addProperty("enabled",true);c.addProperty("accountId",account);c.addProperty("zoneId",z.get("id").getAsString());c.addProperty("zoneName",zone);c.addProperty("tunnelId",id);c.addProperty("tunnelName",t.get("name").getAsString());c.addProperty("tunnelToken",tok);c.addProperty("hostname",host);c.addProperty("serverPort",si.port());save(c);main.accept(()->{s.send("§aNetflared setup complete.");s.send("§6Public address: §f"+host);connect(s);});}catch(Exception e){main.accept(()->s.send("§cSetup failed: "+e.getMessage()));}});}
 private void connect(Sender s){try{JsonObject c=load();if(!configured(c)){if(s!=null)s.send("§cNetflared is not configured.");return;}CompletableFuture.runAsync(()->{try{ensureBinary();Files.writeString(tokenFile,v(c,"tunnelToken"));process=new ProcessBuilder(binary.toString(),"tunnel","run","--token-file",tokenFile.toString()).redirectErrorStream(true).start();main.accept(()->{if(s!=null)s.send("§aCloudflared started.");});}catch(Exception e){main.accept(()->{if(s!=null)s.send("§cCould not start tunnel: "+e.getMessage());});}});}catch(Exception e){if(s!=null)s.send("§cCould not load configuration: "+e.getMessage());}}
 private void ensureBinary()throws Exception{if(Files.isRegularFile(binary))return;Files.createDirectories(binary.getParent());String arch=System.getProperty("os.arch","").contains("aarch64")?"arm64":"amd64";String asset=System.getProperty("os.name","").toLowerCase().contains("win")?"cloudflared-windows-"+arch+".exe":"cloudflared-linux-"+arch;String release=http.send(HttpRequest.newBuilder(URI.create("https://api.github.com/repos/cloudflare/cloudflared/releases/latest")).header("User-Agent","Netflared-Server").build(),HttpResponse.BodyHandlers.ofString()).body();for(JsonElement e:JsonParser.parseString(release).getAsJsonObject().getAsJsonArray("assets")){JsonObject a=e.getAsJsonObject();if(asset.equals(a.get("name").getAsString())){try(InputStream in=http.send(HttpRequest.newBuilder(URI.create(a.get("browser_download_url").getAsString())).header("User-Agent","Netflared-Server").build(),HttpResponse.BodyHandlers.ofInputStream()).body()){Files.copy(in,binary,StandardCopyOption.REPLACE_EXISTING);}binary.toFile().setExecutable(true);return;}}throw new IOException("No cloudflared binary for this platform.");}
 private void status(Sender s){try{JsonObject c=load();if(!configured(c)){s.send("§eNetflared is not configured.");return;}s.send("§6Netflared status");s.send("§7Address: §f"+v(c,"hostname"));s.send("§7Local: §f127.0.0.1:"+c.get("serverPort").getAsInt());s.send("§7Tunnel: "+(process!=null&&process.isAlive()?"§aCONNECTED":"§cSTOPPED"));}catch(Exception e){s.send("§c"+e.getMessage());}}
 private void info(Sender s){try{JsonObject c=load();s.send("§6Netflared configuration");s.send("§7Public hostname: §f"+v(c,"hostname"));s.send("§7Minecraft port: §f"+c.get("serverPort").getAsInt());s.send("§7Cloudflare zone: §f"+v(c,"zoneName"));s.send("§7Tunnel: §f"+v(c,"tunnelName"));}catch(Exception e){s.send("§c"+e.getMessage());}}
 private void reset(Sender s){shutdown();try{JsonObject c=load();c.addProperty("enabled",false);c.addProperty("tunnelToken","");c.addProperty("tunnelId","");c.addProperty("tunnelName","");c.addProperty("hostname","");save(c);Files.deleteIfExists(tokenFile);s.send("§aLocal configuration reset. Cloudflare resources were left untouched.");}catch(Exception e){s.send("§cReset failed: "+e.getMessage());}}
 private void help(Sender s){s.send("§6Netflared Server");s.send("§7/netflared status");s.send("§7/netflared info");s.send("§7/netflared setup <token>");s.send("§7/netflared setup select <number> [subdomain]");s.send("§7/netflared connect|disconnect|reset");}
 private String request(String method,String url,JsonObject body,String token)throws Exception{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create(url)).header("Authorization","Bearer "+token).header("Accept","application/json");if(body!=null)b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(body.toString()));else b.method(method,HttpRequest.BodyPublishers.noBody());HttpResponse<String>r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());JsonObject j=JsonParser.parseString(r.body()).getAsJsonObject();if(r.statusCode()<200||r.statusCode()>=300||!j.get("success").getAsBoolean())throw new IOException("Cloudflare API request failed (HTTP "+r.statusCode()+")");return r.body();}
}