modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
[[mods]]
modId="netflared"
version="${version}"
displayName="Netflared Server"
description="Cloudflare Tunnel management for Minecraft servers."
authors="matejpcs"
[[dependencies.netflared]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="SERVER"
[[dependencies.netflared]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
